### PR TITLE
Fix include file order

### LINKED ISSUE #390: Jpeg support broken due to wrong include file order
With wgrib2 3.7.0, I get

```
#> wgrib2 tmp.grb2 -small_grib -15:30 35:65 subset.grb2 -set_grib_type jpeg

*** FATAL ERROR: set_grib_type: bad type jpeg ***

*** arg list to wgrib2(..): tmp.grb2 -small_grib -15:30 35:65 subset.grb2 -set_grib_type jpeg
```

This is due to wrong include file order in Grib.c.

### PR DESCRIPTION
**Pull request by manfredsc**
Fixes #390

`wgrib2.h` includes `config.h` which is needed for conditional compilation of features.

So statements like
```
#ifdef USE_G2CLIB_LOW
#include <grib2.h>
#endif
```
need to come after the inclusion of `wgrib2.h`
The files Grib.c, ffopen.c and rd_seq_grib.c are affected by this.

Fix include order and do some minor cleanup.

### CODE REVIEW

File: wgrib2/wgrib2.h [hunk 1]
```diff
@@ -518,10 +514,7 @@ int wrt_sec(unsigned const char *sec0, unsigned const char *sec1, unsigned const
 int scaling(unsigned char **sec, double *base, int *decimal, int *binary, int *nbits);
 unsigned char *mk_bms(float *data, unsigned int *ndata);
 
-int g2c_dec_png(unsigned char *pngbuf, int *width, int *height, unsigned char *cout);
```
Comment (AlysonStahl-NOAA) [inline wgrib2/wgrib2.h:521]: This function is being used so I don't think we want to remove this line

**Review by AlysonStahl-NOAA — CHANGES_REQUESTED** [review]

File: wgrib2/wgrib2.h (hunk 1 above)
Comment (manfredsc) [reply wgrib2/wgrib2.h:521]: Yes, it is used, but the prototype of this function is provided by /usr/include/grib2.h (nceplibs-g2c):
```
#> grep -n -A1 g2c_dec_png /usr/include/grib2.h
385:int g2c_dec_png(unsigned char *pngbuf, int *width, int *height,
386-                unsigned char *cout);
```
Furthermore, "g2c_" belongs to the nceplibs-g2c namespace, and declaration of such functions
and prototypes should be provided by nceplibs-g2c. If there would be a local function of this name,
it really should be renamed. But there is no local function of this name, everything OK.
This is simply a duplicate, unneeded declaration of this prototype.

For me, it compiles and runs fine without any additional warnings (using several different GCC
compilers up to version 15.1).

Sorry for mixing this cleanup with the actual bug fix.

Comment (manfredsc) [reply wgrib2/wgrib2.h:521]: And if there would be compile-errors when using a version of nceplibs-g2c without PNG support,
appropriate encapsulations with `#if G2_PNG_ENABLED` would be needed, and no additional prototype insertions.

Comment (manfredsc) [reply wgrib2/wgrib2.h:521]: Hmm, I just looked after the g2_ namespace. There is a duplicate prototype declaration of g2_unpack3 in GDT.c

Comment (AlysonStahl-NOAA) [reply wgrib2/wgrib2.h:521]: Whoops, you're right. We can remove it then.

Comment (AlysonStahl-NOAA) [reply wgrib2/wgrib2.h:521]: > Hmm, I just looked after the g2_ namespace. There is a duplicate prototype declaration of g2_unpack3 in GDT.c

Thanks for pointing this out. We want to reduce these duplicates where we can. I'll look into this.

**Review by AlysonStahl-NOAA — APPROVED** [review]
