### PR TITLE
fix gctpc*s omer

### LINKED ISSUE #451: fix  gctpc's omerforint and omerinvint (warning uninitialized f)
When compiling the gctpc library, omerforint and omerinvint have warnings
that f is uninitialized.  This does not affect wgrib2 but the library should
be fixed.
   1.  wgrib2 does not support Oblique Mercator
   2.  f is used in a report

### PR DESCRIPTION
**Pull request by webisu**
Fixes #451 
Part of #444 

variable "f" is undefined when fabs(lat_origin) < 1e-10

Following the code when |f| > 1e-10,  you find that f== 1.0
So set f=1 when |f| < 1e-10.

### CODE REVIEW

**Comment by webisu** [comment]
Typo: last two lines should replace |f| by |lat_origin|.

**Comment by webisu** [comment]
This is for issue #451

File: wgrib2/gctpc/source/omerfor.c [hunk 1]
```diff
@@ -65,6 +65,7 @@ static double cosaz;		/**< Cos of azimuth */
  * - 202 :: Input data error
  * 
  * @author T. Mittan @date March, 1993
```
Comment (AlysonStahl-NOAA) [inline wgrib2/gctpc/source/omerfor.c:73]: The placement of your name and date won't format correctly in the documentation pages.

I've been following what other NCEP Libraries are doing to track changes. Insert the following lines, either at the top of both files below the "Algorithm References Section" or somewhere in the function description (maybe below the author line):

```c
 * ### Program History Log
 * Date | Programmer | Comments
 * -----|------------|---------
 * 3/1993 | T. Mittan | Initial implementation
 * 9/2025 | W. Ebisuzaki | defined f
``` 

Maybe just add it to the function description since it's not for the whole file.

File: wgrib2/gctpc/source/omerinv.c [hunk 2]
```diff
@@ -67,6 +67,7 @@ static double cosaz;		/**< Cos of azimuth */
  * - 202 :: Input data error
  * 
  * @author T. Mittan @date March, 1993
+ *         W. Ebisuzaki Sep 2025 define f
```
Comment (AlysonStahl-NOAA) [inline wgrib2/gctpc/source/omerinv.c]: See my other comment

**Comment by AlysonStahl-NOAA** [comment]
We want to release version 3.8.0 soon, so if you want this included please make these requested changes

**Review by AlysonStahl-NOAA — APPROVED** [review]
